name: si_kasir
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  image_picker: ^1.1.2
  flutter_masked_text2: ^0.9.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  cloud_firestore: ^5.6.0
  excel: ^4.0.6
  open_file: ^3.5.10
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  fl_chart: ^0.70.0
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.3.1
  intl: ^0.18.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  mobile_scanner: ^6.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google.png
    - assets/icons/login.png
    - assets/icons/register.png
    - assets/produk/
    - assets/profile.jpeg
    - assets/qris.jpeg
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
